const fs=require('fs'),p=require('path'),crypto=require('crypto');
const versao=process.argv[2]||'v01',versaoInv=process.argv[3]||'v02';
const dir=p.join(__dirname,'etapa-1-curriculo',versao),root='C:/Users/wmors/Videos/KatoMart Acelerado';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const inv=read(p.join(__dirname,'etapa-0-inventario',versaoInv,'INVENTARIO.json')),physical=read(p.join(__dirname,'etapa-0-inventario',versaoInv,'ARQUIVOS-FISICOS.json'));
const h=read(p.join(dir,'MAPA-HABILIDADES.json')).habilidades,a=read(p.join(dir,'AULAS-PROPOSTAS.json')).aulasPropostas;
function csv(file){const t=fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'');let rows=[],row=[],cell='',q=false;for(let j=0;j<t.length;j++){const c=t[j];if(c==='"'){if(q&&t[j+1]==='"'){cell+='"';j++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if(c==='\n'&&!q){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const head=rows.shift();return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(head.map((k,j)=>[k,r[j]||''])));}
const matrix=csv(p.join(dir,'MATRIZ-FONTE-AULA.csv')),evidence=csv(p.join(dir,'EVIDENCIAS.csv'));
const hm=new Map(h.map(x=>[x.id,x])),am=new Map(a.map(x=>[x.id,x])),fm=new Map(physical.arquivos.map(x=>[x.id,x])),im=new Map(inv.entradas.map(x=>[x.id,x])),em=new Set(evidence.map(x=>x.evidencia_id));
const out={data:new Date().toISOString(),limites:'Revisão documental e referencial; nenhum vídeo reproduzido ou PDF renderizado',etapa0:{arquivos:physical.arquivos.length,tamanhosDivergentes:[],idsArquivosDuplicados:physical.arquivos.length-fm.size,referencesDivergentes:[],hashesAmostra:[]},etapa1:{habilidades:h.length,aulas:a.length,dominiosReais:[...new Set(h.map(x=>x.dominio))],grafoHabilidades:[],grafoAulas:[],matriz:{linhas:matrix.length,entradasUnicas:new Set(matrix.map(x=>x.entradaOrigemId)).size,semDestinoReal:0,habilidadesInexistentes:0,evidenciasInexistentes:0,arquivosIncompativeis:[]},habilidadesSemAula:[],fontesPropostasAusentes:[],relacoesPropostasAusentes:[],estadosMatriz:[...new Set(matrix.map(x=>x.nivelInspecao))]}};
for(const f of physical.arquivos){try{if(fs.statSync(p.join(root,f.caminhoRelativo)).size!==f.tamanhoBytes)out.etapa0.tamanhosDivergentes.push(f.id);}catch{out.etapa0.tamanhosDivergentes.push(f.id);}}
for(const e of inv.entradas)for(const f of e.arquivos){const x=fm.get(f.arquivoId);if(!x||x.caminhoRelativo!==f.caminhoRelativo||x.sha256!==f.sha256||x.tamanhoBytes!==f.tamanhoBytes)out.etapa0.referencesDivergentes.push({entrada:e.id,arquivo:f.arquivoId});}
function graph(arr,map,field){const errors=[],seen=new Set(),active=new Set();function dfs(id){if(active.has(id)){errors.push({ciclo:id});return;}if(seen.has(id))return;seen.add(id);active.add(id);for(const pre of map.get(id)[field]||[]){if(!map.has(pre))errors.push({id,ausente:pre});else dfs(pre);}active.delete(id);}for(const x of arr)dfs(x.id);return errors;}
out.etapa1.grafoHabilidades=graph(h,hm,'prerequisitos');out.etapa1.grafoAulas=graph(a,am,'prerequisitosAulas');
for(const row of matrix){if(!am.has(row.aulaPropostaId))out.etapa1.matriz.semDestinoReal++;if(!hm.has(row.habilidadeId))out.etapa1.matriz.habilidadesInexistentes++;if(!em.has(row.evidenciaId))out.etapa1.matriz.evidenciasInexistentes++;if(row.arquivoId){const f=fm.get(row.arquivoId);if(!f||!im.get(row.entradaOrigemId)?.arquivos.some(x=>x.arquivoId===row.arquivoId))out.etapa1.matriz.arquivosIncompativeis.push({entrada:row.entradaOrigemId,arquivo:row.arquivoId});}}
for(const x of h)if(!a.some(y=>y.habilidadePrincipalId===x.id||y.habilidadesSecundarias?.includes(x.id)))out.etapa1.habilidadesSemAula.push({id:x.id,nome:x.nome});
for(const x of a)for(const source of x.fontesCandidatas){if(!im.has(source))out.etapa1.fontesPropostasAusentes.push({aula:x.id,source});if(!matrix.some(r=>r.entradaOrigemId===source&&r.aulaPropostaId===x.id))out.etapa1.relacoesPropostasAusentes.push({aula:x.id,source});}
out.etapa1.arquivosCitadosCalibracao=[...new Set(fs.readFileSync(p.join(dir,'CALIBRACAO-SEIS-AULAS.md'),'utf8').match(/arq-\d+/g)||[])].map(id=>({id,real:fm.get(id)?.caminhoRelativo,bytes:fm.get(id)?.tamanhoBytes,sha256:fm.get(id)?.sha256}));
if(fs.existsSync(p.join(dir,'DESTINOS-EDITORIAIS.json'))){const dm=new Set(read(p.join(dir,'DESTINOS-EDITORIAIS.json')).destinos.map(d=>d.id));out.etapa1.destinosModelados={linhasComDestino:matrix.filter(r=>dm.has(r.destinoEditorialId)).length,linhasSemAulaNemDestino:matrix.filter(r=>!am.has(r.aulaPropostaId)&&!dm.has(r.destinoEditorialId)).length,habilidadesPreenchidasInexistentes:matrix.filter(r=>r.habilidadeId&&!hm.has(r.habilidadeId)).length,nota:'Contagens anteriores de semDestinoReal/ habilidadesInexistentes incluem campos vazios legítimos; usar estas contagens para versões com destinos modelados'};}
if(fs.existsSync(p.join(dir,'CANDIDATOS-CALIBRACAO.json'))){out.etapa1.candidatosDivergentes=[];const c=read(p.join(dir,'CANDIDATOS-CALIBRACAO.json'));for(const x of c.candidatos)for(const f of x.arquivosFisicos){const real=fm.get(f.arquivoId);if(!real||['caminhoRelativo','tamanhoBytes','sha256'].some(k=>real[k]!==f[k])||!im.get(x.entradaOrigemId)?.arquivos.some(r=>r.arquivoId===f.arquivoId))out.etapa1.candidatosDivergentes.push({candidato:x.candidatoId,arquivo:f.arquivoId});}}
async function hash(file){const c=crypto.createHash('sha256');for await(const b of fs.createReadStream(file))c.update(b);return c.digest('hex');}
(async()=>{for(const f of physical.arquivos.filter(x=>x.caminhoRelativo.includes('Partituras fáceis para iniciantes/0. '))){const real=await hash(p.join(root,f.caminhoRelativo));out.etapa0.hashesAmostra.push({id:f.id,real,declarado:f.sha256,confere:real===f.sha256});}fs.writeFileSync(p.join(__dirname,`etapa-1-curriculo/EVIDENCIAS-REVISAO-CODEX-${versao}.json`),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({...out,etapa1:{...out.etapa1,arquivosCitadosCalibracao:out.etapa1.arquivosCitadosCalibracao.slice(0,3)}},null,2));})();
